export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";
export const CREATE_RECEIVER_ID = "CREATE_RECEIVER_ID";
export const CREATE_RECEIVER_NAME = "CREATE_RECEIVER_NAME";
export const UPDATE_CHAT = "UPDATE_CHAT";
