export const REGISTER_FORM = "REGISTER_FORM";
export const REGISTER_FORM_SUBMIT = "REGISTER_FORM_SUBMIT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const CLEAR_REGISTER_FORM = "CLEAR_REGISTER_FORM";
